config/routes.rb
Rails.application.routes.draw do
  root 'calculadora#new'

  get  'como-funciona', to: 'home#comofunciona'
  get  'a-empresa',     to: 'home#aempresa'
  get  'search',        to: 'home#search'

  resources :contacts,    only: [:new, :create]
  resources :calculadora, only: [:new, :create]

  get  'orcamento', to: 'calculadora#orcamento'
  post 'orcamento', to: 'calculadora#orcamento'

  get  'resultado',    to: 'calculadora#resultado'
  get  'download_pdf', to: 'calculadora#download_pdf'
  post 'resultado',    to: 'calculadora#resultado'

  get 'cities_by_state', to: 'cities#cities_by_state'
  get 'state_by_city',   to: 'states#state_by_city'
  get 'fee_by_state',    to: 'states#fee_by_state'
end

app/models/calculadora.rb
class Calculadora
  include ActiveModel::Model

  attr_accessor :rede_eletrica, :estado, :cidade, :local, :ajuste, :media, :source
  attr_accessor :nome, :telefone, :email
  attr_accessor :pdf_name

  validates_presence_of :rede_eletrica, :estado, :cidade, :local, :media, if: :acesso_a_rede_eletrica?
  validates_presence_of :rede_eletrica, :nome, :telefone, :email, unless: :acesso_a_rede_eletrica?
  validates_presence_of :ajuste, unless: :offgrid?

  HUMANIZED_ATTRIBUTES = {
      local:  'Tipo do local da instalação',
      ajuste: 'Ajuste da tarifa',
      media:  'Energia por mês'
  }

  MEDIA_DIAS_POR_MES   = 30
  MEDIA_HORAS_BRASIL   = 5
  MEDIA_MINIMA         = 3800
  MEDIA_MAXIMA         = 4500
  NUMERO_MESES_ANO     = 12
  NUMERO_MESES_25_ANOS = NUMERO_MESES_ANO * 25
  POTENCIA_MEDIA_PLACA = 330
  EFICIENCIA_PAINEL    = 0.83

  def self.human_attribute_name(attr, options = {}) # 'options' wasn't available in Rails 3, and prior versions.
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  def kwp
    kw = (media.to_f / ajuste_ou_default.to_f).round(2)

    step_1 = kw.to_f / MEDIA_DIAS_POR_MES.to_f
    step_2 = step_1.to_f / MEDIA_HORAS_BRASIL.to_f
    step_3 = step_2 / EFICIENCIA_PAINEL

    step_3.round(2)
  end

  def ajuste_ou_default
    ajuste.nil? ? get_taxa_sem_ajuste : ajuste.to_f
  end

  def investimento_minimo
    kwp * MEDIA_MINIMA
  end

  def investimento_maximo
    kwp * MEDIA_MAXIMA
  end

  def media_aritmetica
    (investimento_minimo + investimento_maximo) / 2
  end

  def economia_mensal
    media.to_f
  end

  def economia_anual
    economia_mensal * NUMERO_MESES_ANO
  end

  def economia_25_anos
    economia_mensal * NUMERO_MESES_25_ANOS
  end

  def retorno
    (media_aritmetica / economia_mensal) / NUMERO_MESES_ANO
  end

  def cidade_nome
    city_repository.find(cidade).name
  end

  def qtd_paineis
    ((kwp / POTENCIA_MEDIA_PLACA * 1000)).round
  end

  def geracao_media
    (economia_mensal / ajuste_ou_default.to_f).to_i
  end

  private

  def acesso_a_rede_eletrica?
    rede_eletrica == 'sim'
  end

  def offgrid?
    source == 'off-grid'
  end

  def get_taxa_sem_ajuste
    state = state_repository.find(estado)

    case local
    when 'residencial'
      state.residencial
    when 'comercial'
      state.comercial
    when 'outro'
      state.outro
    else
      state.residencial
    end

  end

  def city_repository
    City
  end

  def state_repository
    State
  end
end

app/controllers/calculadora_controller.rb
class CalculadoraController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @calculadora = Calculadora.new

    if params[:mail] == 'sent'
      flash
      @calculadora.rede_eletrica = 'sim'
    else
      @calculadora.rede_eletrica = 'sim'
    end
  end

  def resultado
    @calculadora = Calculadora.new(calculadora_params)

    if @calculadora.valid?
      if calculadora_params[:rede_eletrica] == 'nao'
        @contact = Contact.new(calculadora_params)
        ContactMailer.contact_message(@contact, 'Nova mensagem recebida / Off-grid').deliver! if Rails.env.production?
        redirect_to new_calculadora_path(mail: 'sent'), notice: 'OBRIGADO. ENTRAREMOS EM CONTATO EM BREVE!'
      end
    else
      render action: 'new'
    end
  end

  def orcamento
    if request.get?
      @calculadora = Calculadora.new

      @calculadora.local  = params[:local]         if params[:local]
      @calculadora.media  = params[:media]         if params[:media]
      @calculadora.ajuste = params[:ajuste]        if params[:ajuste]
      @calculadora.cidade = params[:cidade]        if params[:cidade]
      @calculadora.estado = params[:estado]        if params[:estado]
    else
      @contact = Contact.new(calculadora_params)
      ContactMailer.contact_message(@contact, 'Nova mensagem recebida / Orçamento').deliver! if Rails.env.production?

      @calculadora = Calculadora.new(calculadora_params)

      # generate pdf file
      date     = Time.now.strftime('%d/%m/%Y')
      pdf_name = Time.now.to_i

      template_filename = "#{Rails.root}/public/pdf/proposta_comercial_01.pdf"
      nome = @calculadora.nome

      Prawn::Document.generate("#{Rails.root}/public/pdf/temp.pdf", :skip_page_creation => true) do
        start_new_page(:template => template_filename)
        bounding_box([0,80], :width => 525, :height => 30) do
          text_box nome, :size => 15, :width => 525, :height => 300, align: :right
        end
      end

      pdf_page01 = CombinePDF.load "#{Rails.root}/public/pdf/temp.pdf"
      pdf_page02 = CombinePDF.load "#{Rails.root}/public/pdf/proposta_comercial_02.pdf"
      pdf_page03 = CombinePDF.load "#{Rails.root}/public/pdf/proposta_comercial_03.pdf"

      # page 01
      pdf_page01.pages[0].textbox date,              height: 20, width: 70, y: 125, x: 490, font_size: 15
      # pdf_page01.pages[0].textbox @calculadora.nome, height: 10, width: 70, y: 110, x: 460, font_size: 15

      # page 02
      pdf_page02.pages[0].textbox @calculadora.qtd_paineis.to_s + '',                                                  height: 10, width: 70, y: 570, x: 460, font_size: 12
      pdf_page02.pages[0].textbox @calculadora.kwp.to_s + ' kWp',                                                      height: 10, width: 70, y: 570, x: 340, font_size: 12
      pdf_page02.pages[0].textbox 'R$ ' + ActiveSupport::NumberHelper.number_to_delimited(@calculadora.media).to_s,    height: 10, width: 70, y: 570, x: 220, font_size: 12
      pdf_page02.pages[0].textbox @calculadora.geracao_media.to_s + " kWh",                                        height: 10, width: 70, y: 570, x: 120, font_size: 12

      pdf_page02.pages[0].textbox 'R$ ' + ActiveSupport::NumberHelper.number_to_delimited(@calculadora.economia_25_anos).to_s,    height: 10, width: 70, y: 450, x: 460, font_size: 12
      pdf_page02.pages[0].textbox 'R$ ' + ActiveSupport::NumberHelper.number_to_delimited(@calculadora.economia_anual).to_s,      height: 10, width: 70, y: 450, x: 360, font_size: 12
      pdf_page02.pages[0].textbox @calculadora.retorno.to_d.truncate(1).to_s + ' ANOS',                                           height: 10, width: 70, y: 450, x: 230, font_size: 12
      pdf_page02.pages[0].textbox 'R$ ' + ActiveSupport::NumberHelper.number_to_delimited(@calculadora.media_aritmetica.round(2)).to_s, height: 10, width: 70, y: 450, x: 110, font_size: 12


      pdf = CombinePDF.new
      pdf << pdf_page01
      pdf << pdf_page02
      pdf << pdf_page03

      # pdf.save "#{Rails.root}/public/pdf/output#{pdf_name}.pdf"

      NotificationMailer.envia_pdf_cliente(@calculadora, 'Norte Sul Energia - Orçamento',pdf.to_pdf).deliver!
      NotificationMailer.envia_pdf_empresa(@calculadora, 'Norte Sul Energia - Orçamento', pdf.to_pdf).deliver!

      send_data pdf.to_pdf, filename: 'orcamento.pdf', type: 'application/pdf; charset=utf-8', encoding: "utf8"
    end
  end

  def download_pdf
    pdf = CombinePDF.load "#{Rails.root}/public/pdf/output#{params[:pdf_name]}.pdf"

    send_data pdf.to_pdf, filename: 'orcamento.pdf', type: 'application/pdf'

    #File.delete("#{Rails.root}/public/pdf/output#{params[:pdf_name]}.pdf")
  end

  private

  def calculadora_params
    params.require(:calculadora).permit(:rede_eletrica, :estado, :cidade, :local, :ajuste, :media, :nome, :email, :telefone, :source) if params[:calculadora]
  end

end

app/views/calculadora/orcamento.html.erb
<header class="orcamento">
  <div class="container">

    <%= render partial:'layouts/shared/links', locals: { carouselClass: '' } %>

    <br>

    <br><br><br>

  </div>
</header>

<section class="services">
  <div class="container">
    <div class="box first">

      <div class="row">
        <div class="row">
          <div class="col-md-12">
            <div class="nav-left-text correct-paragraph">
            <div class="rdg-expertise-description rdg-strategy-bg rdg-animated-delay-0-contact" style="float: left;"></div>
              <p>O MELHOR INVESTIMENTO</p>
              <p>SOLICITE UM ORÇAMENTO</p>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">

          <div class="row">
          <p class="paragraph-inside">
            Para receber um orçamento sem compromisso da NORTE SUL basta preencher os campos do formulário
            abaixo. A nossa equipe entrará em contato o mais breve possível.
          </p>
            </div>

          <br>

          <div class="col-md-12">
          <%= simple_form_for @calculadora, url: url_for(action: 'orcamento', controller: 'calculadora'), method: 'post' do |f| %>
            <%= f.hidden_field :media %>
            <%#= f.hidden_field :ajuste, value: @calculadora.ajuste %>
            <%= hidden_field_tag :previous_local_value, @calculadora.local %>
            <%= hidden_field_tag :previous_media_value, @calculadora.media %>


            <div class="form-group">
              <div class="col-md-12">
                <%= f.input :nome, placeholder: 'NOME', required: true, label: false, input_html: { class: 'form-control'} %>
              </diV>

              <div class="col-md-12">
                <%= f.input :email, placeholder: 'E-MAIL', required: true, label: false, input_html: { class: 'form-control'} %>
              </diV>

              <div class="col-md-12">
                <%= f.input :telefone, placeholder: 'TELEFONE', required: true, label: false, input_html: { class: 'form-control', style: 'margin-bottom: 40px'} %>
              </div>
            </div>

            <div class="row">
              <p style="font-size: 26px; text-align: center;">
                LOCAL DA INSTALAÇÃO
              </p>
            </div>

            <div class="col-md-6">
              <%= f.input :estado, prompt: 'ESTADO', collection: State.all, required: true, label: false, input_html: { class: 'form-control'}, sytle: 'padding-right: 1px' %>
            </div>

            <div class="col-md-6">
              <%= f.input :cidade, prompt: 'CIDADE', collection: City.all, required: true, label: false, input_html: { class: 'form-control'} %>
            </div>

            <div id="extra-space-orcamento"></div>

            <div class="row">
              <p style="font-size: 26px; text-align: center;">ONDE SERÁ INSTALADO?</p>
            </div>

            <div class="instalacao-wrapper">
              <%= f.collection_radio_buttons(:local, [['residencial', '/icons/residencial_azul'], ['comercial', '/icons/comercial_azul'], ['outro', '/icons/outro_azul']], :first, :last, required: true, item_wrapper_tag: "div class='col-md-3 col-md-offset-1'", class: 'threads-opts') do |b| %>
                <%= b.label { b.radio_button(class: 'threads-opts') + image_tag(b.text+'.png', style: 'width: 70%') + local_dictionary(b.text) } %>
              <% end %>
            </div>

            <div class="row">
              <div class="col-md-6 col-md-offset-3 ajuste">
                <%= f.input :ajuste, required: true, label: false, placeholder: 'AJUSTE DA TARIFA EM R$', input_html: { class: 'form-control center-block', style: 'text-align: center;'} %>
              </div>
            </div>

            <div class="row">
                <p style="font-size: 26px; text-align: center; margin-top: 40px">CONSUMO MÉDIO MENSAL (KWH)</p>
              </div>

            <div class="valor-slider">
              <div class="slider-wrapper">
                <div class="slider-items dollar-sign">
                  <%= image_tag 'menor.png', style: 'height: 20px;margin-left: 20px', class: 'pull-right' %>
                </div>
                <div class="slider-items inside-slider">
                  <div id="slider"></div>
                </div>
                <div class="slider-items dollar-sign">
                  <%= image_tag 'maior.png', style: 'height: 40px' %>
                </div>
              </div>
            </div>

            <center class="submit-content"> <%= f.button :submit, 'ENVIAR', :class=> "btn btn-primary", style: 'width: 250px' %> </center>

          <% end %>
          </div>
        </div><!--/.box-->
      </div>
    </div>
  </div><!--/.container-->
</section>

<script>
    $(document).ready(function(){
        let startAmount = 7500;
        var local = '';

        initPreferences = function () {
            $('#calculadora_telefone').phoneBrazil();

            if ($('#previous_media_value').val() !== ''){
                startAmount = parseInt($('#previous_media_value').val());
            }

            if ($('#previous_local_value').val() != undefined){
                clickLocal($('#calculadora_local_' + $('#previous_local_value').val()).val());
            }

            //Added, set initial value.
            $("#amount").val(startAmount);
            $("#duration").val(startAmount);
            $("#amount-label").text(startAmount);
            $("#duration-label").text(startAmount);
            $('#calculadora_media').val(startAmount);

            update();
            editValue();
        }();

      $('#calculadora_ajuste').data('holder',$('#calculadora_ajuste').attr('placeholder'));
      $('#calculadora_ajuste').focusin(function(){
        $(this).attr('placeholder','');
      });
      $('#calculadora_ajuste').focusout(function(){
        $(this).attr('placeholder',$(this).data('holder'));
      });

      $("input[name='calculadora[local]']").click(function(){
            local = $(this).val();
            getFeeByState(local);
            clickLocal(local);
        });

        function clickLocal(type) {

            switch(type) {
                case 'residencial':
                    $('#calculadora_local_residencial').next('img').attr("src", "/icons/residencial_amarelo.png");
                    $('#calculadora_local_comercial').next('img').attr("src", "/icons/comercial_azul.png");
                    $('#calculadora_local_outro').next('img').attr("src", "/icons/outro_azul.png");

                    break;

                case 'comercial':
                    $('#calculadora_local_residencial').next('img').attr("src", "/icons/residencial_azul.png");
                    $('#calculadora_local_comercial').next('img').attr("src", "/icons/comercial_amarelo.png");
                    $('#calculadora_local_outro').next('img').attr("src", "/icons/outro_azul.png");

                    break;

                case 'outro':
                    $('#calculadora_local_residencial').next('img').attr("src", "/icons/residencial_azul.png");
                    $('#calculadora_local_comercial').next('img').attr("src", "/icons/comercial_azul.png");
                    $('#calculadora_local_outro').next('img').attr("src", "/icons/outro_amarelo.png");

                    break;
            }
        }

        $("#calculadora_estado").change(function() {
            getCitiesByState("id="+$("#calculadora_estado").val());

            getFeeByState(local);
        });

        function getFeeByState(local) {

            if(local != '' && $("#calculadora_estado").val() != undefined) {

                $.ajax({
                    type: 'GET',
                    data:{
                        state_id: $("#calculadora_estado").val(),
                        local:    local,
                    },
                    url: '/fee_by_state/',

                    success: function(data){
                        switch(local) {
                            case 'residencial':
                                $("#calculadora_ajuste").val(data['state']['residencial']);
                                break;
                            case 'comercial':
                                $("#calculadora_ajuste").val(data['state']['comercial']);
                                break;
                            case 'outro':
                                $("#calculadora_ajuste").val('');
                                $("#calculadora_ajuste").focus();
                                break;
                        }
                    }
                });
            }
        }

        $("#calculadora_estado").change(function() {
            getCitiesByState("id="+$("#calculadora_estado").val());
        });

        $("#calculadora_cidade").change(function() {
            getStateByCity("id="+$("#calculadora_cidade").val());
        });

        function getCitiesByState(id) {
            $.getJSON("/cities_by_state", id, function (j) {
                var options = '<option value="">CIDADE</option>';
                $.each(j.cty, function (i, item) {
                    options += '<option value="' + item.id + '">' + item.n + '</option>';
                });
                $("#calculadora_cidade").html(options);
            });
        }

        function getStateByCity(id) {
            $.getJSON("/state_by_city", id, function (j) {
                $("#calculadora_estado").val(j['state']['id']);
            });
        }

        $("#slider").slider({
            animate: true,
            value:startAmount,
            min: 100,
            max: 15000,
            step: 10,
            slide: function(event, ui) {
                update(1,ui.value);
            }
        });


        $('#slider a').html('<label class="editable"> '+ startAmount +' </label>');

        editValue();


        function editValue() {

          if($(".ui-slider-handle").is(":visible") == true){
            $('.ui-slider-handle').css('left', '45%');
          }


            $('#slider').on('click', "label.editable", function() {

                var $lbl = $(this), o = parseInt($lbl.text()),
                    $txt = $('<input type="number" class="editable-label-text" value="'+o+'" />');
                $lbl.replaceWith($txt);
                $txt.focus();

                $txt.blur(function() {
                    $txt.replaceWith($lbl);

                })
                    .keydown(function(evt){
                        if(evt.keyCode == 13) {
                            var no = $(this).val();
                            $lbl.text(no);
                            $txt.replaceWith($lbl);

                            $("#slider" ).slider('value', no);
                            $('#calculadora_media').val(no);
                        }
                    });

                $txt.blur(function() {
                    $txt.replaceWith($lbl);

                }).focusout(function() {
                    var no = $(this).val();
                    $lbl.text(no);
                    $txt.replaceWith($lbl);

                    $("#slider" ).slider('value', no);
                    $('#calculadora_media').val(no);
                })

            });
        }

        //changed. now with parameter
        function update(slider,val) {
            //changed. Now, directly take value from ui.value. if not set (initial, will use current value.)
            var $amount = slider == 1?val:$("#amount").val();
            var $duration = slider == 2?val:$("#duration").val();

            /* commented
            $amount = $( "#slider" ).slider( "value" );
             */

            $total = "$" + ($amount * $duration);
            $( "#amount" ).val($amount);
            $( "#amount-label" ).text($amount);
            $( "#duration" ).val($duration);
            $( "#duration-label" ).text($duration);
            $( "#total" ).val($total);
            $( "#total-label" ).text($total);

            $('#slider a').html('<label class="editable">'+$amount+'</label>');

            if ($amount != undefined) {
              $('#calculadora_media').val($amount);
            }
        }
    });
</script>

app/views/calculadora/resultado.html.erb
<%= render 'layouts/shared/carousel', slide: 2 %>

<%= hidden_field_tag :pdf_name, @pdf_name %>

<section class="services">
  <div class="container">
    <div class="box carousel">

      <div class="row">
        <div class="col-md-12">

          <%= link_to 'Download', download_pdf_path(pdf_name: @pdf_name), id: 'download_pdf', class: 'download_pdf' %>

          <div id="init"></div>

          <div class="row">
            <div class="nav-main-text" style="text-align: center;font-size: 60px;font-weight: 600;">
              <div id="calculadora">CALCULADORA SOLAR</div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <figure class="card card-product">
            <figcaption class="info-wrap">
              <h4 class="title card-title"><%= image_tag '/icons/resultado_investimento.png', style: 'height: 50px; border: 0; padding: 0' %>INVESTIMENTO</h4>
            </figcaption>
            <div class="bottom-wrap">
              <p>De <%= number_to_currency(@calculadora.investimento_minimo) %> a <%= number_to_currency(@calculadora.investimento_maximo) %></p>
              <hr style="height:2px;border:none;color:gray;background-color:gray;padding-left: 50px;width: 50px;">
              <p>Economia mensal:</p>
              <p><%= number_to_currency(@calculadora.media) %></p>
              <p>Economia anual:</p>
              <p><%= number_to_currency(@calculadora.economia_anual) %></p>
              <p>Economia total em 25 anos:</p>
              <p><%= number_to_currency(@calculadora.economia_25_anos) %></p>
            </div>
          </figure>
        </div>

        <div class="col-md-4">
          <figure class="card card-product">
            <figcaption class="info-wrap">
              <h4 class="title card-title"><%= image_tag '/icons/resultado_ambiente.png', style: 'height: 50px; border: 0; padding: 0' %>AMBIENTE</h4>
            </figcaption>
            <div class="bottom-wrap">
              <p>Equivalente a 10.000 KM de </p>
              <p>carro elétrico</p>
              <hr style="height:2px;border:none;color:gray;background-color:gray;padding-left: 50px;width: 50px;">
              <p>Redução de CO2 na atmosfera</p>
              <p>Equivalente a centenas  de árvores plantadas</p>
              <p>Equivalente a milhares  de KM rodados de um  carro</p>
            </div>
          </figure>
        </div>

        <div class="col-md-4">
          <figure class="card card-product">
            <figcaption class="info-wrap">
              <h4 class="title card-title"><%= image_tag '/icons/resultado_sistema.png', style: 'height: 50px; border: 0; padding: 0' %>SISTEMA INDICADO</h4>
            </figcaption>
            <div class="bottom-wrap">
              <div class="text-center">
                <p style="padding-top: 16px; padding-bottom: 16px"><%= number_with_delimiter(@calculadora.kwp.round(2)) %> kWp</p>
              </div>
              <hr style="height:2px;border:none;color:gray;background-color:gray;padding-left: 50px;width: 50px;">
              <p>Tamanho da Potência:</p>
              <p><%= number_with_delimiter(@calculadora.kwp.round(2)) %> kWp</p>
              <p>Número de Módulos:</p>
              <p><%= @calculadora.qtd_paineis %> módulos</p>
              <p>Produção Estimada:</p>
              <p><%= @calculadora.geracao_media %> kw/h</p>
            </div>
          </figure>
        </div>
      </div>

      <div class="col-md-6">
        <%= link_to 'REINCIAR CALCULADORA', new_calculadora_path(anchor: 'calculadora'), class: 'btn btn-primary btn-block pull-right' %>
      </div>

      <div class="col-md-6">
        <%= link_to 'SOLICITE ORÇAMENTO', orcamento_path(
                                                        media:   params[:calculadora][:media],
                                                        estado:  params[:calculadora][:estado],
                                                        cidade:  params[:calculadora][:cidade],
                                                        local:   params[:calculadora][:local],
                                                        ajuste:  params[:calculadora][:ajuste],
                                                        ), class: 'btn btn-primary-outline btn-block pull-left' %>
      </div>

      <br><br><br>

    </div>
  </div>
</section>

<script>
    $(document).ready(function(){
        init = function () {
            //$('#download_pdf')[0].click();
            //$(window).scrollTop($('#download_pdf').offset().top);
        }();
    });
</script>